package(
    default_visibility = ["//visibility:public"],
)


cc_library(
    name = "hello_world_calculator",
    srcs = ["hello_world_calculator.cc"],
    deps = [
       "@mediapipe//mediapipe/framework:calculator_framework",
        "@com_google_absl//absl/memory",
    ],
    alwayslink = 1,
)